version: '3.8'

services:

  server:
    build:
      context: .
      target: development
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DB_URL: "mongodb://db:27017/user"
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: user
    volumes:
      - user:/data/db

volumes:
  user:
